# Project Euler Problem 2:
# Each new term in the Finobacci sequence is generated by adding
# the previous two terms. By starting with 1 and 2, the first 10
# terms will be:
#       1,2,3,5,8,13,21,34,55,89,...
# By considering the terms in the Finobacci sequence whose values 
# do not exceed four million, find the sum of the even-valued
# terms.

def main():
    finobacci_all = []
    finobacci_even = []
    
    finobacci_all.append(1)
    finobacci_all.append(2)

    while finobacci_all[-1] < 4000000:
        generated = finobacci_all[-1] + finobacci_all[-2]
        finobacci_all.append(generated)
    # Delete the last item because generated last item exceeds 4 million
    finobacci_all.pop(-1)

    for i in finobacci_all:
        if i % 2 == 0:
            finobacci_even.append(i)

    total = sum(finobacci_even)
    print("The sum of even Finobacci numbers are: ", total)

if __name__ == '__main__':
    main()

