'''
The sequence of triangle numbers is generated by adding the natural numbers. So
the 7th triangle number would be 1+2+3+4+5+6+7=28. The first ten terms would be:
1,3,6,10,15,21,28,36,45,55,...
Let us list the factors of the first seven triangle numbers:
1:  1
3:  1,3
6:  1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors. What
is the value of the first triangle number to have over five hundred divisors?
'''
# Reference from: https://www.mathblog.dk/triangle-number-with-more-than-500-divisors/

import math
import numpy as np

def divCount(n): 
    nod=0
    sqrt=int(math.sqrt(n))
    list=np.arange(1,sqrt+1)
    for i in list:
        if n%i==0:
            nod+=2
    if sqrt*sqrt==n:
        nod-=1
    return nod

def main():
    n=0
    i=1
    while divCount(n)<500:
        n+=i
        i+=1
    print(n)

if __name__ == '__main__':
    main()
